### ISSUE TITLE
Add Functionality to Access Quotes (Random, Tags, Author)

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/quotes#4]
It's all well and good having a [`quotes.json`](https://github.com/nelsonic/quotes/blob/master/quotes.json) file with a bunch of quotes.
But how are we going to _access_ those quotes from `Elixir`?!

# Story

As a person wanting to use thought-provoking quotes in my project,
I need an easy way of getting a _single_ quote to display
so that the users of my app can be inspired/motivated to get stuff done!

# Todo

+ [ ] Create an Elixir Module that has functions for returning a single quote:
  + [ ] `random` - get a random quote for any author or topic `Quotes.random()`
  + [ ] `tag` - get a quote by a specific tag e.g: `Quotes.tag("time")`
  + [ ] `author` - get a random quote by a specific author e.g: `Quotes.author("Einstein")`

**Comment by nelsonic** [comment]
It's just occurred to me that if we execute a `Quotes.random_by_tag` function
and no match is found, will it _explode_...?
